### ISSUE TITLE
Can't compile on Ubuntu 16.04 x86

### ISSUE THREAD

**Issue by questin** [flier/pyfasthash#15]
running install
running bdist_egg
running egg_info
writing pyhash.egg-info/PKG-INFO
writing top-level names to pyhash.egg-info/top_level.txt
writing dependency_links to pyhash.egg-info/dependency_links.txt
reading manifest file 'pyhash.egg-info/SOURCES.txt'
writing manifest file 'pyhash.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-i686/egg
running install_lib
running build_py
running build_ext
building '_pyhash' extension
i686-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DBOOST_PYTHON_STATIC_LIB -I/usr/include/python2.7 -c src/Hash.cpp -o build/temp.linux-i686-2.7/src/Hash.o -msse4.2
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from src/Hash.cpp:1:0:
src/Hash.h:20:20: error: expected unqualified-id before ‘__int128’
   typedef unsigned __int128 uint128_t;
                    ^
In file included from src/Hash.cpp:1:0:
src/Hash.h:74:34: error: ‘uint128_t’ does not name a type
   inline PyObject *convert(const uint128_t& value)
                                  ^
src/Hash.h:74:20: error: redefinition of ‘PyObject* internal::convert(const T&) [with T = int; PyObject = _object]’
   inline PyObject *convert(const uint128_t& value)
                    ^
src/Hash.h:38:20: note: ‘PyObject* internal::convert(const T&) [with T = int; PyObject = _object]’ previously declared here
   inline PyObject *convert(const int& value)
                    ^
src/Hash.h:148:1: error: ‘uint128_t’ does not name a type
 uint128_t extract_hash_value<uint128_t>(PyObject *obj)
 ^
In file included from src/Hash.cpp:4:0:
src/MurmurHash.h:49:18: error: ‘uint128_t’ was not declared in this scope
 typedef murmur_t<uint128_t, uint32_t, murmur_hash3_x86_128> murmur3_x86_128_t;
                  ^
src/MurmurHash.h:49:59: error: template argument 1 is invalid
 typedef murmur_t<uint128_t, uint32_t, murmur_hash3_x86_128> murmur3_x86_128_t;

**Comment by flier** [comment]
Which GCC version you are using?

> gcc -v
 Using built-in specs.
 COLLECT_GCC=gcc
 COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~ 16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

**Comment by pengyusong** [comment]
same question, my gcc version is: 

```
(graphite) [root@MONITOR_SERVER ~]# gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) 
```

**Comment by pengyusong** [comment]
@flier i finally use version 0.4, but it‘s may be inappropriate. so what's the solution
