### ISSUE TITLE
pip install pyshash on windows failed

### ISSUE THREAD

**Issue by Slach** [flier/pyfasthash#8]
steps to reproduce
install python 2.7 32bit from http://python.org/
install VC for Python http://aka.ms/vcpython27
download and unpack boost from http://heanet.dl.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.7z

pip install failed with following errors

<pre>
SET PYTHON_HOME=C:\Python27\
SET BOOST_HOME=C:\Boost\boost_1_58_0\
pip install pyhash

Collecting pyhash
  Using cached pyhash-0.6.2.tar.gz
Installing collected packages: pyhash
  Running setup.py install for pyhash
    Complete output from command D:\Portable\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\e11c7~1.kli\\appdata\\local\\temp\\pip-build-9hnleq\\pyhash\\setup.py';exec(compi
e(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\e11c7~1.kli\appdata\local\temp\pip-rhsqea-record\install-record.txt --single-ve
sion-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    copying pyhash.py -> build\lib.win32-2.7
    running build_ext
    building '_pyhash' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\src
    creating build\temp.win32-2.7\Release\src\fnv
    creating build\temp.win32-2.7\Release\src\lookup3
    creating build\temp.win32-2.7\Release\src\SuperFastHash
    creating build\temp.win32-2.7\Release\src\smhasher
    C:\Users\e.klimov\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DBOOST_PYTHON_STATIC_LIB -DWIN32 -ID:\Portable\Boost\boost_
_58_0\ -ID:\Portable\Python27\include -ID:\Portable\Python27\include -ID:\Portable\Python27\PC /Tpsrc\Hash.cpp /Fobuild\temp.win32-2.7\Release\src\Hash.obj /O2 /GL /MT /EHsc /Gy /Zi
    cl : Command line warning D9025 : overriding '/MD' with '/MT'
    Hash.cpp
    c:\users\e.klimov\appdata\local\temp\pip-build-9hnleq\pyhash\src\CityHash.h(66) : error C2451: conditional expression of type 'uint128_t' is illegal
            No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
    c:\users\e.klimov\appdata\local\temp\pip-build-9hnleq\pyhash\src\smhasher\pstdint.h(309) : warning C4005: 'UINT8_C' : macro redefinition
            D:\Portable\Boost\boost_1_58_0\boost/cstdint.hpp(448) : see previous definition of 'UINT8_C'
    c:\users\e.klimov\appdata\local\temp\pip-build-9hnleq\pyhash\src\smhasher\pstdint.h(324) : warning C4005: 'INT8_C' : macro redefinition
            D:\Portable\Boost\boost_1_58_0\boost/cstdint.hpp(433) : see previous definition of 'INT8_C'
    c:\users\e.klimov\appdata\local\temp\pip-build-9hnleq\pyhash\src\smhasher\pstdint.h(342) : warning C4005: 'UINT16_C' : macro redefinition
            D:\Portable\Boost\boost_1_58_0\boost/cstdint.hpp(451) : see previous definition of 'UINT16_C'
    c:\users\e.klimov\appdata\local\temp\pip-build-9hnleq\pyhash\src\smhasher\pstdint.h(366) : warning C4005: 'INT16_C' : macro redefinition
            D:\Portable\Boost\boost_1_58_0\boost/cstdint.hpp(436) : see previous definition of 'INT16_C'
    c:\users\e.klimov\appdata\local\temp\pip-build-9hnleq\pyhash\src\smhasher\pstdint.h(386) : warning C4005: 'UINT32_C' : macro redefinition
            D:\Portable\Boost\boost_1_58_0\boost/cstdint.hpp(454) : see previous definition of 'UINT32_C'
    c:\users\e.klimov\appdata\local\temp\pip-build-9hnleq\pyhash\src\smhasher\pstdint.h(415) : warning C4005: 'INT32_C' : macro redefinition
            D:\Portable\Boost\boost_1_58_0\boost/cstdint.hpp(439) : see previous definition of 'INT32_C'
    c:\users\e.klimov\appdata\local\temp\pip-build-9hnleq\pyhash\src\smhasher\pstdint.h(480) : warning C4005: 'UINT64_C' : macro redefinition
            D:\Portable\Boost\boost_1_58_0\boost/cstdint.hpp(457) : see previous definition of 'UINT64_C'
    c:\users\e.klimov\appdata\local\temp\pip-build-9hnleq\pyhash\src\smhasher\pstdint.h(481) : warning C4005: 'INT64_C' : macro redefinition
            D:\Portable\Boost\boost_1_58_0\boost/cstdint.hpp(442) : see previous definition of 'INT64_C'
    c:\users\e.klimov\appdata\local\temp\pip-build-9hnleq\pyhash\src\smhasher\pstdint.h(547) : warning C4005: 'UINTMAX_C' : macro redefinition
            D:\Portable\Boost\boost_1_58_0\boost/cstdint.hpp(461) : see previous definition of 'UINTMAX_C'
    c:\users\e.klimov\appdata\local\temp\pip-build-9hnleq\pyhash\src\smhasher\pstdint.h(548) : warning C4005: 'INTMAX_C' : macro redefinition
            D:\Portable\Boost\boost_1_58_0\boost/cstdint.hpp(460) : see previous definition of 'INTMAX_C'
    c:\users\e.klimov\appdata\local\temp\pip-build-9hnleq\pyhash\src\SpookyHash.h(49) : error C2059: syntax error : '{'
    c:\users\e.klimov\appdata\local\temp\pip-build-9hnleq\pyhash\src\SpookyHash.h(49) : error C2143: syntax error : missing ';' before '{'
    c:\users\e.klimov\appdata\local\temp\pip-build-9hnleq\pyhash\src\SpookyHash.h(49) : error C2143: syntax error : missing ';' before '.'
    error: command 'C:\\Users\\e.klimov\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "D:\Portable\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\e11c7~1.kli\\appdata\\local\\temp\\pip-build-9hnleq\\pyhash\\setup.py';exec(compile(getattr(tokenize, 'op
n', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\e11c7~1.kli\appdata\local\temp\pip-rhsqea-record\install-record.txt --single-version-externally-managed
--compile" failed with error code 1 in c:\users\e11c7~1.kli\appdata\local\temp\pip-build-9hnleq\pyhash
</pre>

**Comment by Slach** [comment]
compilation error changes after upgrade to 0.8
see  https://github.com/rurban/smhasher/issues/30 for details

**Comment by Slach** [comment]
successfull build recipe
```
SET BOOST_HOME=C:\Boost\boost_1_58_0\
SET VS100COMNTOOLS=%VS140COMNTOOLS%
SET DISTUTILS_USE_SDK=1
SET MSSdk=1
cd %BOOST_HOME%
bootstrap.bat
b2.exe toolset=msvc threadapi=win32 link=static runtime-link=static variant=release address-model=64 --with-python --build-type=complete
pip install pyhash
```
